// <auto-generated />
using Database_and_web_assignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database_and_web_assignment.Migrations
{
    [DbContext(typeof(Database_and_web_assignmentContext))]
    [Migration("20201216075224_Courses")]
    partial class Courses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database_and_web_assignment.models.Admins", b =>
                {
                    b.Property<int>("Admin_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Admin_Address")
                        .HasColumnType("int");

                    b.Property<int>("Admin_Email")
                        .HasColumnType("int");

                    b.Property<int>("Admin_First_Name")
                        .HasColumnType("int");

                    b.Property<int>("Admin_Last_Name")
                        .HasColumnType("int");

                    b.Property<int>("Admin_Mobile_Number")
                        .HasColumnType("int");

                    b.HasKey("Admin_ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Database_and_web_assignment.models.Courses", b =>
                {
                    b.Property<int>("Course_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Course_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Course_ID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Database_and_web_assignment.models.Students", b =>
                {
                    b.Property<int>("Student_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Course_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Mobile_Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student_ID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Database_and_web_assignment.models.Teachers", b =>
                {
                    b.Property<int>("Teacher_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Teacher_Address")
                        .HasColumnType("int");

                    b.Property<int>("Teacher_Email")
                        .HasColumnType("int");

                    b.Property<int>("Teacher_First_Name")
                        .HasColumnType("int");

                    b.Property<int>("Teacher_Last_Name")
                        .HasColumnType("int");

                    b.Property<int>("Teacher_Mobile_Number")
                        .HasColumnType("int");

                    b.HasKey("Teacher_ID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Database_and_web_assignment.models.Venues", b =>
                {
                    b.Property<int>("Venue_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Venue_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Venue_ID");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("Database_and_web_assignment.models.logins", b =>
                {
                    b.Property<int>("Login_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Login_ID");

                    b.ToTable("logins");
                });
#pragma warning restore 612, 618
        }
    }
}
